name: crowdknock_flutter
description: Aplicación Flutter de CrowdKnock
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  go_router: ^13.0.1
  json_annotation: ^4.9.0
  url_launcher: ^6.2.6
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
