dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  go_router: ^13.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

dependencies:
  shared_preferences: ^2.2.2

dependencies:
  go_router: ^13.0.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
