version: '3.8'

services:
  db:
    image: postgres:15
    container_name: crowdknock_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: crowduser
      POSTGRES_PASSWORD: crowdpass
      POSTGRES_DB: crowdknockdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: crowdknock_backend
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: crowduser
      DB_PASSWORD: crowdpass
      DB_NAME: crowdknockdb
      JWT_SECRET: supersecret123
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "src/server.js"]

volumes:
  pgdata:
