### Enviar participación con comentario + imagen JPG como evidencia

POST http://localhost:4000/api/challenges/CHALLENGE_ID_AQUI/submissions
Authorization: Bearer {{TOKEN_AQUI}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="comment"

Participación con foto de evidencia.
--boundary
Content-Disposition: form-data; name="file"; filename="evidencia.jpg"
Content-Type: image/jpeg

< ./ejemplos/evidencia.jpg
--boundary--

