name: crowdknock_admin
description: Panel de administración para CrowdKnock (Flutter Web)
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  go_router: ^13.0.1

dependencies:
  flutter:
    sdk: flutter

  # UI y visualización
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  fl_chart: ^0.66.1
  responsive_framework: ^1.1.1

  # Navegación
  go_router: ^13.0.1

  # Estado (elige uno: provider o riverpod)
  provider: ^6.1.2
  # riverpod: ^3.0.0 # ✅ Descomenta solo si decides migrar completamente a Riverpod

  # HTTP y lógica de backend
  http: ^1.2.1
  jwt_decoder: ^2.0.1
  universal_html: ^2.2.4
  intl: ^0.19.0
  logger: ^2.2.0

  # Hooks (útil si usas flutter_hooks + provider)
  flutter_hooks: ^0.20.5

  # Utilidades
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

