name: crowdknock_admin
description: Panel de administración para CrowdKnock (Flutter Web)
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & diseño
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  fl_chart: ^0.66.1

  # Estado y lógica
  provider: ^6.1.2
  riverpod: ^3.0.0 # opcional si migras a lógica reactiva más escalable

  # HTTP & backend
  http: ^1.2.1
  intl: ^0.19.0

  # Utilidades
  responsive_framework: ^1.1.1
  url_launcher: ^6.2.6
  logger: ^2.2.0

  # JWT y manejo de tokens
  jwt_decoder: ^2.0.1

  # Web support
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

