openapi: 3.0.3
info:
  title: CrowdKnock API
  version: 1.0.0
  description: API REST protegida con JWT para la plataforma CrowdKnock
servers:
  - url: http://localhost:3000
    description: Servidor local de desarrollo

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: Credenciales inválidas

security:
  - bearerAuth: []

paths:
  /auth/login:
    post:
      summary: Iniciar sesión
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: admin@crowdknock.com
                password:
                  type: string
                  example: admin123
      responses:
        '200':
          description: Login exitoso, retorna token y datos del usuario
        '401':
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/me:
    get:
      summary: Obtener datos del usuario autenticado
      tags: [Auth]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Usuario autenticado
        '401':
          description: No autorizado

  /metrics/daily:
    get:
      summary: Métricas diarias
      tags: [Metrics]
      responses:
        '200':
          description: Datos de métricas diarias

  /metrics/users:
    get:
      summary: Métricas de usuarios
      tags: [Metrics]
      responses:
        '200':
          description: Estadísticas de usuarios

  /metrics/content:
    get:
      summary: Métricas de contenido
      tags: [Metrics]
      responses:
        '200':
          description: Estadísticas de contenido

  /metrics/challenges:
    get:
      summary: Métricas de desafíos
      tags: [Metrics]
      responses:
        '200':
          description: Estadísticas de desafíos

  /moderation/reports:
    get:
      summary: Obtener reportes pendientes
      tags: [Moderation]
      responses:
        '200':
          description: Lista de contenido/comentarios reportados

  /users:
    get:
      summary: Listar usuarios
      tags: [Users]
      responses:
        '200':
          description: Lista de usuarios

  /settings:
    get:
      summary: Obtener configuración
      tags: [Settings]
      responses:
        '200':
          description: Configuración general de la plataforma

  /system/status:
    get:
      summary: Estado del sistema
      tags: [System]
      responses:
        '200':
          description: Estado actual del sistema
